// Code generated by DarwinKit. DO NOT EDIT.

package virtualization

import (
	"unsafe"

	"github.com/progrium/darwinkit/objc"
)

// The class instance for the [AudioDeviceConfiguration] class.
var AudioDeviceConfigurationClass = _AudioDeviceConfigurationClass{objc.GetClass("VZAudioDeviceConfiguration")}

type _AudioDeviceConfigurationClass struct {
	objc.Class
}

// An interface definition for the [AudioDeviceConfiguration] class.
type IAudioDeviceConfiguration interface {
	objc.IObject
}

// The base class for an audio device configuration. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzaudiodeviceconfiguration?language=objc
type AudioDeviceConfiguration struct {
	objc.Object
}

func AudioDeviceConfigurationFrom(ptr unsafe.Pointer) AudioDeviceConfiguration {
	return AudioDeviceConfiguration{
		Object: objc.ObjectFrom(ptr),
	}
}

func (ac _AudioDeviceConfigurationClass) Alloc() AudioDeviceConfiguration {
	rv := objc.Call[AudioDeviceConfiguration](ac, objc.Sel("alloc"))
	return rv
}

func (ac _AudioDeviceConfigurationClass) New() AudioDeviceConfiguration {
	rv := objc.Call[AudioDeviceConfiguration](ac, objc.Sel("new"))
	rv.Autorelease()
	return rv
}

func NewAudioDeviceConfiguration() AudioDeviceConfiguration {
	return AudioDeviceConfigurationClass.New()
}

func (a_ AudioDeviceConfiguration) Init() AudioDeviceConfiguration {
	rv := objc.Call[AudioDeviceConfiguration](a_, objc.Sel("init"))
	return rv
}
