// Code generated by DarwinKit. DO NOT EDIT.

package virtualization

import (
	"unsafe"

	"github.com/progrium/darwinkit/objc"
)

// The class instance for the [GraphicsDevice] class.
var GraphicsDeviceClass = _GraphicsDeviceClass{objc.GetClass("VZGraphicsDevice")}

type _GraphicsDeviceClass struct {
	objc.Class
}

// An interface definition for the [GraphicsDevice] class.
type IGraphicsDevice interface {
	objc.IObject
	Displays() []GraphicsDisplay
}

// A class that represents a graphics device in a VM. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzgraphicsdevice?language=objc
type GraphicsDevice struct {
	objc.Object
}

func GraphicsDeviceFrom(ptr unsafe.Pointer) GraphicsDevice {
	return GraphicsDevice{
		Object: objc.ObjectFrom(ptr),
	}
}

func (gc _GraphicsDeviceClass) Alloc() GraphicsDevice {
	rv := objc.Call[GraphicsDevice](gc, objc.Sel("alloc"))
	return rv
}

func (gc _GraphicsDeviceClass) New() GraphicsDevice {
	rv := objc.Call[GraphicsDevice](gc, objc.Sel("new"))
	rv.Autorelease()
	return rv
}

func NewGraphicsDevice() GraphicsDevice {
	return GraphicsDeviceClass.New()
}

func (g_ GraphicsDevice) Init() GraphicsDevice {
	rv := objc.Call[GraphicsDevice](g_, objc.Sel("init"))
	return rv
}

// The list of graphics displays configured for this graphics device. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzgraphicsdevice/4168486-displays?language=objc
func (g_ GraphicsDevice) Displays() []GraphicsDisplay {
	rv := objc.Call[[]GraphicsDisplay](g_, objc.Sel("displays"))
	return rv
}
