// Code generated by DarwinKit. DO NOT EDIT.

package virtualization

import (
	"github.com/progrium/darwinkit/objc"
)

// A protocol you implement to observe state changes in graphic displays. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzgraphicsdisplayobserver?language=objc
type PGraphicsDisplayObserver interface {
	// optional
	DisplayDidBeginReconfiguration(display GraphicsDisplay)
	HasDisplayDidBeginReconfiguration() bool

	// optional
	DisplayDidEndReconfiguration(display GraphicsDisplay)
	HasDisplayDidEndReconfiguration() bool
}

// ensure impl type implements protocol interface
var _ PGraphicsDisplayObserver = (*GraphicsDisplayObserverObject)(nil)

// A concrete type for the [PGraphicsDisplayObserver] protocol.
type GraphicsDisplayObserverObject struct {
	objc.Object
}

func (g_ GraphicsDisplayObserverObject) HasDisplayDidBeginReconfiguration() bool {
	return g_.RespondsToSelector(objc.Sel("displayDidBeginReconfiguration:"))
}

// The method the framework calls when the reconfiguration operation has begun. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzgraphicsdisplayobserver/4168494-displaydidbeginreconfiguration?language=objc
func (g_ GraphicsDisplayObserverObject) DisplayDidBeginReconfiguration(display GraphicsDisplay) {
	objc.Call[objc.Void](g_, objc.Sel("displayDidBeginReconfiguration:"), display)
}

func (g_ GraphicsDisplayObserverObject) HasDisplayDidEndReconfiguration() bool {
	return g_.RespondsToSelector(objc.Sel("displayDidEndReconfiguration:"))
}

// The method the framework calls when the reconfiguration operation ends. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzgraphicsdisplayobserver/4168495-displaydidendreconfiguration?language=objc
func (g_ GraphicsDisplayObserverObject) DisplayDidEndReconfiguration(display GraphicsDisplay) {
	objc.Call[objc.Void](g_, objc.Sel("displayDidEndReconfiguration:"), display)
}
