// Code generated by DarwinKit. DO NOT EDIT.

#import "Virtualization/Virtualization.h"

void importVirtualizationProtocols() {
    id o;
    o = @protocol(VZGraphicsDisplayObserver);
    o = @protocol(VZNetworkBlockDeviceStorageDeviceAttachmentDelegate);
    o = @protocol(VZVirtioConsoleDeviceDelegate);
    o = @protocol(VZVirtioSocketListenerDelegate);
    o = @protocol(VZVirtualMachineDelegate);
}
