// Code generated by DarwinKit. DO NOT EDIT.

package virtualization

import (
	"unsafe"

	"github.com/progrium/darwinkit/objc"
)

// The class instance for the [USBMassStorageDeviceConfiguration] class.
var USBMassStorageDeviceConfigurationClass = _USBMassStorageDeviceConfigurationClass{objc.GetClass("VZUSBMassStorageDeviceConfiguration")}

type _USBMassStorageDeviceConfigurationClass struct {
	objc.Class
}

// An interface definition for the [USBMassStorageDeviceConfiguration] class.
type IUSBMassStorageDeviceConfiguration interface {
	IStorageDeviceConfiguration
}

// The configuration object that represents a USB Mass storage device. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzusbmassstoragedeviceconfiguration?language=objc
type USBMassStorageDeviceConfiguration struct {
	StorageDeviceConfiguration
}

func USBMassStorageDeviceConfigurationFrom(ptr unsafe.Pointer) USBMassStorageDeviceConfiguration {
	return USBMassStorageDeviceConfiguration{
		StorageDeviceConfiguration: StorageDeviceConfigurationFrom(ptr),
	}
}

func (u_ USBMassStorageDeviceConfiguration) InitWithAttachment(attachment IStorageDeviceAttachment) USBMassStorageDeviceConfiguration {
	rv := objc.Call[USBMassStorageDeviceConfiguration](u_, objc.Sel("initWithAttachment:"), attachment)
	return rv
}

// Creates a new storage device configuration with the specified attachment. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/virtualization/vzusbmassstoragedeviceconfiguration/3945424-initwithattachment?language=objc
func NewUSBMassStorageDeviceConfigurationWithAttachment(attachment IStorageDeviceAttachment) USBMassStorageDeviceConfiguration {
	instance := USBMassStorageDeviceConfigurationClass.Alloc().InitWithAttachment(attachment)
	instance.Autorelease()
	return instance
}

func (uc _USBMassStorageDeviceConfigurationClass) Alloc() USBMassStorageDeviceConfiguration {
	rv := objc.Call[USBMassStorageDeviceConfiguration](uc, objc.Sel("alloc"))
	return rv
}

func (uc _USBMassStorageDeviceConfigurationClass) New() USBMassStorageDeviceConfiguration {
	rv := objc.Call[USBMassStorageDeviceConfiguration](uc, objc.Sel("new"))
	rv.Autorelease()
	return rv
}

func NewUSBMassStorageDeviceConfiguration() USBMassStorageDeviceConfiguration {
	return USBMassStorageDeviceConfigurationClass.New()
}

func (u_ USBMassStorageDeviceConfiguration) Init() USBMassStorageDeviceConfiguration {
	rv := objc.Call[USBMassStorageDeviceConfiguration](u_, objc.Sel("init"))
	return rv
}
