// Code generated by DarwinKit. DO NOT EDIT.

// Provide uniform type identifiers that describe file types for storage or transfer.
//
// [Apple Documentation]
//
// [Apple Documentation]: https://developer.apple.com/documentation/uniformtypeidentifiers?language=objc
package uti
