// Code generated by DarwinKit. DO NOT EDIT.

// Access essential data types, collections, and operating-system services to define the base layer of functionality for your app.
//
// [Apple Documentation]
//
// [Apple Documentation]: https://developer.apple.com/documentation/foundation?language=objc
package foundation
