// Code generated by DarwinKit. DO NOT EDIT.

// Read and write most image file formats, and access an image’s metadata.
//
// [Apple Documentation]
//
// [Apple Documentation]: https://developer.apple.com/documentation/imageio?language=objc
package imageio
