// Code generated by DarwinKit. DO NOT EDIT.

package appkit

import (
	"github.com/progrium/darwinkit/objc"
)

// A set of methods that defines a way to add animation to an existing class with a minimum of API impact. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nsanimatablepropertycontainer?language=objc
type PAnimatablePropertyContainer interface {
	// optional
	AnimationForKey(key AnimatablePropertyKey) objc.Object
	HasAnimationForKey() bool

	// optional
	Animator() objc.Object
	HasAnimator() bool

	// optional
	SetAnimations(value map[AnimatablePropertyKey]objc.Object)
	HasSetAnimations() bool

	// optional
	Animations() map[AnimatablePropertyKey]objc.Object
	HasAnimations() bool
}

// ensure impl type implements protocol interface
var _ PAnimatablePropertyContainer = (*AnimatablePropertyContainerObject)(nil)

// A concrete type for the [PAnimatablePropertyContainer] protocol.
type AnimatablePropertyContainerObject struct {
	objc.Object
}

func (a_ AnimatablePropertyContainerObject) HasAnimationForKey() bool {
	return a_.RespondsToSelector(objc.Sel("animationForKey:"))
}

// Returns the animation that should be performed for the specified key. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nsanimatablepropertycontainer/1526209-animationforkey?language=objc
func (a_ AnimatablePropertyContainerObject) AnimationForKey(key AnimatablePropertyKey) objc.Object {
	rv := objc.Call[objc.Object](a_, objc.Sel("animationForKey:"), key)
	return rv
}

func (a_ AnimatablePropertyContainerObject) HasAnimator() bool {
	return a_.RespondsToSelector(objc.Sel("animator"))
}

// Returns a proxy object for the receiver that can be used to initiate implied animation for property changes. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nsanimatablepropertycontainer/1530511-animator?language=objc
func (a_ AnimatablePropertyContainerObject) Animator() objc.Object {
	rv := objc.Call[objc.Object](a_, objc.Sel("animator"))
	return rv
}

func (a_ AnimatablePropertyContainerObject) HasSetAnimations() bool {
	return a_.RespondsToSelector(objc.Sel("setAnimations:"))
}

// Sets the option dictionary that maps event trigger keys to animation objects. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nsanimatablepropertycontainer/1534096-animations?language=objc
func (a_ AnimatablePropertyContainerObject) SetAnimations(value map[AnimatablePropertyKey]objc.Object) {
	objc.Call[objc.Void](a_, objc.Sel("setAnimations:"), value)
}

func (a_ AnimatablePropertyContainerObject) HasAnimations() bool {
	return a_.RespondsToSelector(objc.Sel("animations"))
}

// Sets the option dictionary that maps event trigger keys to animation objects. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nsanimatablepropertycontainer/1534096-animations?language=objc
func (a_ AnimatablePropertyContainerObject) Animations() map[AnimatablePropertyKey]objc.Object {
	rv := objc.Call[map[AnimatablePropertyKey]objc.Object](a_, objc.Sel("animations"))
	return rv
}
