// Code generated by DarwinKit. DO NOT EDIT.

package appkit

import (
	"github.com/progrium/darwinkit/macos/foundation"
	"github.com/progrium/darwinkit/objc"
)

// A set of optional methods that a window’s delegate can implement to respond to events, such as window resizing, moving, exposing, and minimizing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate?language=objc
type PWindowDelegate interface {
	// optional
	WindowWillUseFullScreenContentSize(window Window, proposedSize foundation.Size) foundation.Size
	HasWindowWillUseFullScreenContentSize() bool

	// optional
	WindowDidMove(notification foundation.Notification)
	HasWindowDidMove() bool

	// optional
	WindowDidDeminiaturize(notification foundation.Notification)
	HasWindowDidDeminiaturize() bool

	// optional
	WindowDidChangeScreenProfile(notification foundation.Notification)
	HasWindowDidChangeScreenProfile() bool

	// optional
	CustomWindowsToEnterFullScreenForWindowOnScreen(window Window, screen Screen) []Window
	HasCustomWindowsToEnterFullScreenForWindowOnScreen() bool

	// optional
	WindowDidChangeScreen(notification foundation.Notification)
	HasWindowDidChangeScreen() bool

	// optional
	WindowWillUseFullScreenPresentationOptions(window Window, proposedOptions ApplicationPresentationOptions) ApplicationPresentationOptions
	HasWindowWillUseFullScreenPresentationOptions() bool

	// optional
	WindowWillBeginSheet(notification foundation.Notification)
	HasWindowWillBeginSheet() bool

	// optional
	WindowWillReturnFieldEditorToObject(sender Window, client objc.Object) objc.Object
	HasWindowWillReturnFieldEditorToObject() bool

	// optional
	WindowShouldClose(sender Window) bool
	HasWindowShouldClose() bool

	// optional
	WindowDidResignKey(notification foundation.Notification)
	HasWindowDidResignKey() bool

	// optional
	WindowDidEndSheet(notification foundation.Notification)
	HasWindowDidEndSheet() bool

	// optional
	WindowDidBecomeKey(notification foundation.Notification)
	HasWindowDidBecomeKey() bool

	// optional
	WindowWillResizeToSize(sender Window, frameSize foundation.Size) foundation.Size
	HasWindowWillResizeToSize() bool

	// optional
	WindowWillMiniaturize(notification foundation.Notification)
	HasWindowWillMiniaturize() bool

	// optional
	WindowWillEncodeRestorableState(window Window, state foundation.Coder)
	HasWindowWillEncodeRestorableState() bool

	// optional
	WindowWillExitVersionBrowser(notification foundation.Notification)
	HasWindowWillExitVersionBrowser() bool

	// optional
	WindowDidEnterFullScreen(notification foundation.Notification)
	HasWindowDidEnterFullScreen() bool

	// optional
	WindowDidResize(notification foundation.Notification)
	HasWindowDidResize() bool

	// optional
	WindowWillMove(notification foundation.Notification)
	HasWindowWillMove() bool

	// optional
	WindowStartCustomAnimationToExitFullScreenWithDuration(window Window, duration foundation.TimeInterval)
	HasWindowStartCustomAnimationToExitFullScreenWithDuration() bool

	// optional
	WindowWillExitFullScreen(notification foundation.Notification)
	HasWindowWillExitFullScreen() bool

	// optional
	WindowShouldPopUpDocumentPathMenu(window Window, menu Menu) bool
	HasWindowShouldPopUpDocumentPathMenu() bool

	// optional
	WindowDidMiniaturize(notification foundation.Notification)
	HasWindowDidMiniaturize() bool

	// optional
	WindowWillReturnUndoManager(window Window) foundation.UndoManager
	HasWindowWillReturnUndoManager() bool

	// optional
	WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(window Window, maxPreferredFrameSize foundation.Size, maxAllowedFrameSize foundation.Size) foundation.Size
	HasWindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize() bool

	// optional
	WindowWillEnterFullScreen(notification foundation.Notification)
	HasWindowWillEnterFullScreen() bool

	// optional
	WindowDidFailToEnterFullScreen(window Window)
	HasWindowDidFailToEnterFullScreen() bool

	// optional
	WindowDidExpose(notification foundation.Notification)
	HasWindowDidExpose() bool

	// optional
	WindowDidEndLiveResize(notification foundation.Notification)
	HasWindowDidEndLiveResize() bool

	// optional
	WindowShouldZoomToFrame(window Window, newFrame foundation.Rect) bool
	HasWindowShouldZoomToFrame() bool

	// optional
	WindowDidBecomeMain(notification foundation.Notification)
	HasWindowDidBecomeMain() bool

	// optional
	WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(window Window, screen Screen, duration foundation.TimeInterval)
	HasWindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration() bool

	// optional
	WindowShouldDragDocumentWithEventFromWithPasteboard(window Window, event Event, dragImageLocation foundation.Point, pasteboard Pasteboard) bool
	HasWindowShouldDragDocumentWithEventFromWithPasteboard() bool

	// optional
	WindowDidDecodeRestorableState(window Window, state foundation.Coder)
	HasWindowDidDecodeRestorableState() bool

	// optional
	WindowWillPositionSheetUsingRect(window Window, sheet Window, rect foundation.Rect) foundation.Rect
	HasWindowWillPositionSheetUsingRect() bool

	// optional
	WindowDidChangeBackingProperties(notification foundation.Notification)
	HasWindowDidChangeBackingProperties() bool

	// optional
	CustomWindowsToEnterFullScreenForWindow(window Window) []Window
	HasCustomWindowsToEnterFullScreenForWindow() bool

	// optional
	WindowWillUseStandardFrameDefaultFrame(window Window, newFrame foundation.Rect) foundation.Rect
	HasWindowWillUseStandardFrameDefaultFrame() bool

	// optional
	WindowDidEnterVersionBrowser(notification foundation.Notification)
	HasWindowDidEnterVersionBrowser() bool

	// optional
	WindowStartCustomAnimationToEnterFullScreenWithDuration(window Window, duration foundation.TimeInterval)
	HasWindowStartCustomAnimationToEnterFullScreenWithDuration() bool

	// optional
	WindowDidResignMain(notification foundation.Notification)
	HasWindowDidResignMain() bool

	// optional
	WindowDidExitVersionBrowser(notification foundation.Notification)
	HasWindowDidExitVersionBrowser() bool

	// optional
	WindowWillClose(notification foundation.Notification)
	HasWindowWillClose() bool

	// optional
	CustomWindowsToExitFullScreenForWindow(window Window) []Window
	HasCustomWindowsToExitFullScreenForWindow() bool

	// optional
	WindowDidUpdate(notification foundation.Notification)
	HasWindowDidUpdate() bool

	// optional
	WindowWillStartLiveResize(notification foundation.Notification)
	HasWindowWillStartLiveResize() bool

	// optional
	WindowDidChangeOcclusionState(notification foundation.Notification)
	HasWindowDidChangeOcclusionState() bool

	// optional
	WindowDidFailToExitFullScreen(window Window)
	HasWindowDidFailToExitFullScreen() bool

	// optional
	WindowDidExitFullScreen(notification foundation.Notification)
	HasWindowDidExitFullScreen() bool

	// optional
	WindowWillEnterVersionBrowser(notification foundation.Notification)
	HasWindowWillEnterVersionBrowser() bool
}

// A delegate implementation builder for the [PWindowDelegate] protocol.
type WindowDelegate struct {
	_WindowWillUseFullScreenContentSize                                  func(window Window, proposedSize foundation.Size) foundation.Size
	_WindowDidMove                                                       func(notification foundation.Notification)
	_WindowDidDeminiaturize                                              func(notification foundation.Notification)
	_WindowDidChangeScreenProfile                                        func(notification foundation.Notification)
	_CustomWindowsToEnterFullScreenForWindowOnScreen                     func(window Window, screen Screen) []Window
	_WindowDidChangeScreen                                               func(notification foundation.Notification)
	_WindowWillUseFullScreenPresentationOptions                          func(window Window, proposedOptions ApplicationPresentationOptions) ApplicationPresentationOptions
	_WindowWillBeginSheet                                                func(notification foundation.Notification)
	_WindowWillReturnFieldEditorToObject                                 func(sender Window, client objc.Object) objc.Object
	_WindowShouldClose                                                   func(sender Window) bool
	_WindowDidResignKey                                                  func(notification foundation.Notification)
	_WindowDidEndSheet                                                   func(notification foundation.Notification)
	_WindowDidBecomeKey                                                  func(notification foundation.Notification)
	_WindowWillResizeToSize                                              func(sender Window, frameSize foundation.Size) foundation.Size
	_WindowWillMiniaturize                                               func(notification foundation.Notification)
	_WindowWillEncodeRestorableState                                     func(window Window, state foundation.Coder)
	_WindowWillExitVersionBrowser                                        func(notification foundation.Notification)
	_WindowDidEnterFullScreen                                            func(notification foundation.Notification)
	_WindowDidResize                                                     func(notification foundation.Notification)
	_WindowWillMove                                                      func(notification foundation.Notification)
	_WindowStartCustomAnimationToExitFullScreenWithDuration              func(window Window, duration foundation.TimeInterval)
	_WindowWillExitFullScreen                                            func(notification foundation.Notification)
	_WindowShouldPopUpDocumentPathMenu                                   func(window Window, menu Menu) bool
	_WindowDidMiniaturize                                                func(notification foundation.Notification)
	_WindowWillReturnUndoManager                                         func(window Window) foundation.UndoManager
	_WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize func(window Window, maxPreferredFrameSize foundation.Size, maxAllowedFrameSize foundation.Size) foundation.Size
	_WindowWillEnterFullScreen                                           func(notification foundation.Notification)
	_WindowDidFailToEnterFullScreen                                      func(window Window)
	_WindowDidExpose                                                     func(notification foundation.Notification)
	_WindowDidEndLiveResize                                              func(notification foundation.Notification)
	_WindowShouldZoomToFrame                                             func(window Window, newFrame foundation.Rect) bool
	_WindowDidBecomeMain                                                 func(notification foundation.Notification)
	_WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration     func(window Window, screen Screen, duration foundation.TimeInterval)
	_WindowShouldDragDocumentWithEventFromWithPasteboard                 func(window Window, event Event, dragImageLocation foundation.Point, pasteboard Pasteboard) bool
	_WindowDidDecodeRestorableState                                      func(window Window, state foundation.Coder)
	_WindowWillPositionSheetUsingRect                                    func(window Window, sheet Window, rect foundation.Rect) foundation.Rect
	_WindowDidChangeBackingProperties                                    func(notification foundation.Notification)
	_CustomWindowsToEnterFullScreenForWindow                             func(window Window) []Window
	_WindowWillUseStandardFrameDefaultFrame                              func(window Window, newFrame foundation.Rect) foundation.Rect
	_WindowDidEnterVersionBrowser                                        func(notification foundation.Notification)
	_WindowStartCustomAnimationToEnterFullScreenWithDuration             func(window Window, duration foundation.TimeInterval)
	_WindowDidResignMain                                                 func(notification foundation.Notification)
	_WindowDidExitVersionBrowser                                         func(notification foundation.Notification)
	_WindowWillClose                                                     func(notification foundation.Notification)
	_CustomWindowsToExitFullScreenForWindow                              func(window Window) []Window
	_WindowDidUpdate                                                     func(notification foundation.Notification)
	_WindowWillStartLiveResize                                           func(notification foundation.Notification)
	_WindowDidChangeOcclusionState                                       func(notification foundation.Notification)
	_WindowDidFailToExitFullScreen                                       func(window Window)
	_WindowDidExitFullScreen                                             func(notification foundation.Notification)
	_WindowWillEnterVersionBrowser                                       func(notification foundation.Notification)
}

func (di *WindowDelegate) HasWindowWillUseFullScreenContentSize() bool {
	return di._WindowWillUseFullScreenContentSize != nil
}

// Called to allow the delegate to modify the full-screen content size. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419282-window?language=objc
func (di *WindowDelegate) SetWindowWillUseFullScreenContentSize(f func(window Window, proposedSize foundation.Size) foundation.Size) {
	di._WindowWillUseFullScreenContentSize = f
}

// Called to allow the delegate to modify the full-screen content size. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419282-window?language=objc
func (di *WindowDelegate) WindowWillUseFullScreenContentSize(window Window, proposedSize foundation.Size) foundation.Size {
	return di._WindowWillUseFullScreenContentSize(window, proposedSize)
}
func (di *WindowDelegate) HasWindowDidMove() bool {
	return di._WindowDidMove != nil
}

// Tells the delegate that the window has moved. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419674-windowdidmove?language=objc
func (di *WindowDelegate) SetWindowDidMove(f func(notification foundation.Notification)) {
	di._WindowDidMove = f
}

// Tells the delegate that the window has moved. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419674-windowdidmove?language=objc
func (di *WindowDelegate) WindowDidMove(notification foundation.Notification) {
	di._WindowDidMove(notification)
}
func (di *WindowDelegate) HasWindowDidDeminiaturize() bool {
	return di._WindowDidDeminiaturize != nil
}

// Tells the delegate that the window has been deminimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419296-windowdiddeminiaturize?language=objc
func (di *WindowDelegate) SetWindowDidDeminiaturize(f func(notification foundation.Notification)) {
	di._WindowDidDeminiaturize = f
}

// Tells the delegate that the window has been deminimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419296-windowdiddeminiaturize?language=objc
func (di *WindowDelegate) WindowDidDeminiaturize(notification foundation.Notification) {
	di._WindowDidDeminiaturize(notification)
}
func (di *WindowDelegate) HasWindowDidChangeScreenProfile() bool {
	return di._WindowDidChangeScreenProfile != nil
}

// Tells the delegate that the window has changed screen display profiles. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419581-windowdidchangescreenprofile?language=objc
func (di *WindowDelegate) SetWindowDidChangeScreenProfile(f func(notification foundation.Notification)) {
	di._WindowDidChangeScreenProfile = f
}

// Tells the delegate that the window has changed screen display profiles. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419581-windowdidchangescreenprofile?language=objc
func (di *WindowDelegate) WindowDidChangeScreenProfile(notification foundation.Notification) {
	di._WindowDidChangeScreenProfile(notification)
}
func (di *WindowDelegate) HasCustomWindowsToEnterFullScreenForWindowOnScreen() bool {
	return di._CustomWindowsToEnterFullScreenForWindowOnScreen != nil
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419557-customwindowstoenterfullscreenfo?language=objc
func (di *WindowDelegate) SetCustomWindowsToEnterFullScreenForWindowOnScreen(f func(window Window, screen Screen) []Window) {
	di._CustomWindowsToEnterFullScreenForWindowOnScreen = f
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419557-customwindowstoenterfullscreenfo?language=objc
func (di *WindowDelegate) CustomWindowsToEnterFullScreenForWindowOnScreen(window Window, screen Screen) []Window {
	return di._CustomWindowsToEnterFullScreenForWindowOnScreen(window, screen)
}
func (di *WindowDelegate) HasWindowDidChangeScreen() bool {
	return di._WindowDidChangeScreen != nil
}

// Tells the delegate that the window has changed screens. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419267-windowdidchangescreen?language=objc
func (di *WindowDelegate) SetWindowDidChangeScreen(f func(notification foundation.Notification)) {
	di._WindowDidChangeScreen = f
}

// Tells the delegate that the window has changed screens. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419267-windowdidchangescreen?language=objc
func (di *WindowDelegate) WindowDidChangeScreen(notification foundation.Notification) {
	di._WindowDidChangeScreen(notification)
}
func (di *WindowDelegate) HasWindowWillUseFullScreenPresentationOptions() bool {
	return di._WindowWillUseFullScreenPresentationOptions != nil
}

// Returns the presentation options the window uses when transitioning to full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419144-window?language=objc
func (di *WindowDelegate) SetWindowWillUseFullScreenPresentationOptions(f func(window Window, proposedOptions ApplicationPresentationOptions) ApplicationPresentationOptions) {
	di._WindowWillUseFullScreenPresentationOptions = f
}

// Returns the presentation options the window uses when transitioning to full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419144-window?language=objc
func (di *WindowDelegate) WindowWillUseFullScreenPresentationOptions(window Window, proposedOptions ApplicationPresentationOptions) ApplicationPresentationOptions {
	return di._WindowWillUseFullScreenPresentationOptions(window, proposedOptions)
}
func (di *WindowDelegate) HasWindowWillBeginSheet() bool {
	return di._WindowWillBeginSheet != nil
}

// Notifies the delegate that the window is about to open a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419408-windowwillbeginsheet?language=objc
func (di *WindowDelegate) SetWindowWillBeginSheet(f func(notification foundation.Notification)) {
	di._WindowWillBeginSheet = f
}

// Notifies the delegate that the window is about to open a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419408-windowwillbeginsheet?language=objc
func (di *WindowDelegate) WindowWillBeginSheet(notification foundation.Notification) {
	di._WindowWillBeginSheet(notification)
}
func (di *WindowDelegate) HasWindowWillReturnFieldEditorToObject() bool {
	return di._WindowWillReturnFieldEditorToObject != nil
}

// Tells the delegate that the field editor for a text-displaying object has been requested. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419416-windowwillreturnfieldeditor?language=objc
func (di *WindowDelegate) SetWindowWillReturnFieldEditorToObject(f func(sender Window, client objc.Object) objc.Object) {
	di._WindowWillReturnFieldEditorToObject = f
}

// Tells the delegate that the field editor for a text-displaying object has been requested. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419416-windowwillreturnfieldeditor?language=objc
func (di *WindowDelegate) WindowWillReturnFieldEditorToObject(sender Window, client objc.Object) objc.Object {
	return di._WindowWillReturnFieldEditorToObject(sender, client)
}
func (di *WindowDelegate) HasWindowShouldClose() bool {
	return di._WindowShouldClose != nil
}

// Tells the delegate that the user has attempted to close a window or the window has received a [appkit/nswindow/performclose] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419380-windowshouldclose?language=objc
func (di *WindowDelegate) SetWindowShouldClose(f func(sender Window) bool) {
	di._WindowShouldClose = f
}

// Tells the delegate that the user has attempted to close a window or the window has received a [appkit/nswindow/performclose] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419380-windowshouldclose?language=objc
func (di *WindowDelegate) WindowShouldClose(sender Window) bool {
	return di._WindowShouldClose(sender)
}
func (di *WindowDelegate) HasWindowDidResignKey() bool {
	return di._WindowDidResignKey != nil
}

// Tells the delegate that the window has resigned key window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419711-windowdidresignkey?language=objc
func (di *WindowDelegate) SetWindowDidResignKey(f func(notification foundation.Notification)) {
	di._WindowDidResignKey = f
}

// Tells the delegate that the window has resigned key window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419711-windowdidresignkey?language=objc
func (di *WindowDelegate) WindowDidResignKey(notification foundation.Notification) {
	di._WindowDidResignKey(notification)
}
func (di *WindowDelegate) HasWindowDidEndSheet() bool {
	return di._WindowDidEndSheet != nil
}

// Tells the delegate that the window has closed a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419773-windowdidendsheet?language=objc
func (di *WindowDelegate) SetWindowDidEndSheet(f func(notification foundation.Notification)) {
	di._WindowDidEndSheet = f
}

// Tells the delegate that the window has closed a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419773-windowdidendsheet?language=objc
func (di *WindowDelegate) WindowDidEndSheet(notification foundation.Notification) {
	di._WindowDidEndSheet(notification)
}
func (di *WindowDelegate) HasWindowDidBecomeKey() bool {
	return di._WindowDidBecomeKey != nil
}

// Tells the delegate that the window has become the key window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419737-windowdidbecomekey?language=objc
func (di *WindowDelegate) SetWindowDidBecomeKey(f func(notification foundation.Notification)) {
	di._WindowDidBecomeKey = f
}

// Tells the delegate that the window has become the key window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419737-windowdidbecomekey?language=objc
func (di *WindowDelegate) WindowDidBecomeKey(notification foundation.Notification) {
	di._WindowDidBecomeKey(notification)
}
func (di *WindowDelegate) HasWindowWillResizeToSize() bool {
	return di._WindowWillResizeToSize != nil
}

// Tells the delegate that the window is being resized (whether by the user or through one of the setFrame... methods other than [appkit/nswindow/setframe]). [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419292-windowwillresize?language=objc
func (di *WindowDelegate) SetWindowWillResizeToSize(f func(sender Window, frameSize foundation.Size) foundation.Size) {
	di._WindowWillResizeToSize = f
}

// Tells the delegate that the window is being resized (whether by the user or through one of the setFrame... methods other than [appkit/nswindow/setframe]). [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419292-windowwillresize?language=objc
func (di *WindowDelegate) WindowWillResizeToSize(sender Window, frameSize foundation.Size) foundation.Size {
	return di._WindowWillResizeToSize(sender, frameSize)
}
func (di *WindowDelegate) HasWindowWillMiniaturize() bool {
	return di._WindowWillMiniaturize != nil
}

// Tells the delegate that the window is about to be minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419461-windowwillminiaturize?language=objc
func (di *WindowDelegate) SetWindowWillMiniaturize(f func(notification foundation.Notification)) {
	di._WindowWillMiniaturize = f
}

// Tells the delegate that the window is about to be minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419461-windowwillminiaturize?language=objc
func (di *WindowDelegate) WindowWillMiniaturize(notification foundation.Notification) {
	di._WindowWillMiniaturize(notification)
}
func (di *WindowDelegate) HasWindowWillEncodeRestorableState() bool {
	return di._WindowWillEncodeRestorableState != nil
}

// Tells the delegate the window is about to add its restorable state to a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419619-window?language=objc
func (di *WindowDelegate) SetWindowWillEncodeRestorableState(f func(window Window, state foundation.Coder)) {
	di._WindowWillEncodeRestorableState = f
}

// Tells the delegate the window is about to add its restorable state to a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419619-window?language=objc
func (di *WindowDelegate) WindowWillEncodeRestorableState(window Window, state foundation.Coder) {
	di._WindowWillEncodeRestorableState(window, state)
}
func (di *WindowDelegate) HasWindowWillExitVersionBrowser() bool {
	return di._WindowWillExitVersionBrowser != nil
}

// Tells the delegate that the window is about to leave version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419252-windowwillexitversionbrowser?language=objc
func (di *WindowDelegate) SetWindowWillExitVersionBrowser(f func(notification foundation.Notification)) {
	di._WindowWillExitVersionBrowser = f
}

// Tells the delegate that the window is about to leave version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419252-windowwillexitversionbrowser?language=objc
func (di *WindowDelegate) WindowWillExitVersionBrowser(notification foundation.Notification) {
	di._WindowWillExitVersionBrowser(notification)
}
func (di *WindowDelegate) HasWindowDidEnterFullScreen() bool {
	return di._WindowDidEnterFullScreen != nil
}

// The window has entered full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419116-windowdidenterfullscreen?language=objc
func (di *WindowDelegate) SetWindowDidEnterFullScreen(f func(notification foundation.Notification)) {
	di._WindowDidEnterFullScreen = f
}

// The window has entered full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419116-windowdidenterfullscreen?language=objc
func (di *WindowDelegate) WindowDidEnterFullScreen(notification foundation.Notification) {
	di._WindowDidEnterFullScreen(notification)
}
func (di *WindowDelegate) HasWindowDidResize() bool {
	return di._WindowDidResize != nil
}

// Tells the delegate that the window has been resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419567-windowdidresize?language=objc
func (di *WindowDelegate) SetWindowDidResize(f func(notification foundation.Notification)) {
	di._WindowDidResize = f
}

// Tells the delegate that the window has been resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419567-windowdidresize?language=objc
func (di *WindowDelegate) WindowDidResize(notification foundation.Notification) {
	di._WindowDidResize(notification)
}
func (di *WindowDelegate) HasWindowWillMove() bool {
	return di._WindowWillMove != nil
}

// Tells the delegate that the window is about to move. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419336-windowwillmove?language=objc
func (di *WindowDelegate) SetWindowWillMove(f func(notification foundation.Notification)) {
	di._WindowWillMove = f
}

// Tells the delegate that the window is about to move. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419336-windowwillmove?language=objc
func (di *WindowDelegate) WindowWillMove(notification foundation.Notification) {
	di._WindowWillMove(notification)
}
func (di *WindowDelegate) HasWindowStartCustomAnimationToExitFullScreenWithDuration() bool {
	return di._WindowStartCustomAnimationToExitFullScreenWithDuration != nil
}

// This method is called to start the window animation out of full-screen mode, including transitioning back to the desktop space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419705-window?language=objc
func (di *WindowDelegate) SetWindowStartCustomAnimationToExitFullScreenWithDuration(f func(window Window, duration foundation.TimeInterval)) {
	di._WindowStartCustomAnimationToExitFullScreenWithDuration = f
}

// This method is called to start the window animation out of full-screen mode, including transitioning back to the desktop space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419705-window?language=objc
func (di *WindowDelegate) WindowStartCustomAnimationToExitFullScreenWithDuration(window Window, duration foundation.TimeInterval) {
	di._WindowStartCustomAnimationToExitFullScreenWithDuration(window, duration)
}
func (di *WindowDelegate) HasWindowWillExitFullScreen() bool {
	return di._WindowWillExitFullScreen != nil
}

// The window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419332-windowwillexitfullscreen?language=objc
func (di *WindowDelegate) SetWindowWillExitFullScreen(f func(notification foundation.Notification)) {
	di._WindowWillExitFullScreen = f
}

// The window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419332-windowwillexitfullscreen?language=objc
func (di *WindowDelegate) WindowWillExitFullScreen(notification foundation.Notification) {
	di._WindowWillExitFullScreen(notification)
}
func (di *WindowDelegate) HasWindowShouldPopUpDocumentPathMenu() bool {
	return di._WindowShouldPopUpDocumentPathMenu != nil
}

// Asks the delegate whether the window displays the title pop-up menu in response to a Command-click or Control-click on its title. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419465-window?language=objc
func (di *WindowDelegate) SetWindowShouldPopUpDocumentPathMenu(f func(window Window, menu Menu) bool) {
	di._WindowShouldPopUpDocumentPathMenu = f
}

// Asks the delegate whether the window displays the title pop-up menu in response to a Command-click or Control-click on its title. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419465-window?language=objc
func (di *WindowDelegate) WindowShouldPopUpDocumentPathMenu(window Window, menu Menu) bool {
	return di._WindowShouldPopUpDocumentPathMenu(window, menu)
}
func (di *WindowDelegate) HasWindowDidMiniaturize() bool {
	return di._WindowDidMiniaturize != nil
}

// Tells the delegate that the window has been minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419621-windowdidminiaturize?language=objc
func (di *WindowDelegate) SetWindowDidMiniaturize(f func(notification foundation.Notification)) {
	di._WindowDidMiniaturize = f
}

// Tells the delegate that the window has been minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419621-windowdidminiaturize?language=objc
func (di *WindowDelegate) WindowDidMiniaturize(notification foundation.Notification) {
	di._WindowDidMiniaturize(notification)
}
func (di *WindowDelegate) HasWindowWillReturnUndoManager() bool {
	return di._WindowWillReturnUndoManager != nil
}

// Tells the delegate that the window’s undo manager has been requested. Returns the appropriate undo manager for the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419745-windowwillreturnundomanager?language=objc
func (di *WindowDelegate) SetWindowWillReturnUndoManager(f func(window Window) foundation.UndoManager) {
	di._WindowWillReturnUndoManager = f
}

// Tells the delegate that the window’s undo manager has been requested. Returns the appropriate undo manager for the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419745-windowwillreturnundomanager?language=objc
func (di *WindowDelegate) WindowWillReturnUndoManager(window Window) foundation.UndoManager {
	return di._WindowWillReturnUndoManager(window)
}
func (di *WindowDelegate) HasWindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize() bool {
	return di._WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize != nil
}

// Tells the delegate the window will resize for presentation during version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419360-window?language=objc
func (di *WindowDelegate) SetWindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(f func(window Window, maxPreferredFrameSize foundation.Size, maxAllowedFrameSize foundation.Size) foundation.Size) {
	di._WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize = f
}

// Tells the delegate the window will resize for presentation during version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419360-window?language=objc
func (di *WindowDelegate) WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(window Window, maxPreferredFrameSize foundation.Size, maxAllowedFrameSize foundation.Size) foundation.Size {
	return di._WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(window, maxPreferredFrameSize, maxAllowedFrameSize)
}
func (di *WindowDelegate) HasWindowWillEnterFullScreen() bool {
	return di._WindowWillEnterFullScreen != nil
}

// The window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419563-windowwillenterfullscreen?language=objc
func (di *WindowDelegate) SetWindowWillEnterFullScreen(f func(notification foundation.Notification)) {
	di._WindowWillEnterFullScreen = f
}

// The window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419563-windowwillenterfullscreen?language=objc
func (di *WindowDelegate) WindowWillEnterFullScreen(notification foundation.Notification) {
	di._WindowWillEnterFullScreen(notification)
}
func (di *WindowDelegate) HasWindowDidFailToEnterFullScreen() bool {
	return di._WindowDidFailToEnterFullScreen != nil
}

// Called if the window failed to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419591-windowdidfailtoenterfullscreen?language=objc
func (di *WindowDelegate) SetWindowDidFailToEnterFullScreen(f func(window Window)) {
	di._WindowDidFailToEnterFullScreen = f
}

// Called if the window failed to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419591-windowdidfailtoenterfullscreen?language=objc
func (di *WindowDelegate) WindowDidFailToEnterFullScreen(window Window) {
	di._WindowDidFailToEnterFullScreen(window)
}
func (di *WindowDelegate) HasWindowDidExpose() bool {
	return di._WindowDidExpose != nil
}

// Tells the delegate that the window has been exposed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419258-windowdidexpose?language=objc
func (di *WindowDelegate) SetWindowDidExpose(f func(notification foundation.Notification)) {
	di._WindowDidExpose = f
}

// Tells the delegate that the window has been exposed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419258-windowdidexpose?language=objc
func (di *WindowDelegate) WindowDidExpose(notification foundation.Notification) {
	di._WindowDidExpose(notification)
}
func (di *WindowDelegate) HasWindowDidEndLiveResize() bool {
	return di._WindowDidEndLiveResize != nil
}

// Tells the delegate that a live resize operation on the window has ended. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419150-windowdidendliveresize?language=objc
func (di *WindowDelegate) SetWindowDidEndLiveResize(f func(notification foundation.Notification)) {
	di._WindowDidEndLiveResize = f
}

// Tells the delegate that a live resize operation on the window has ended. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419150-windowdidendliveresize?language=objc
func (di *WindowDelegate) WindowDidEndLiveResize(notification foundation.Notification) {
	di._WindowDidEndLiveResize(notification)
}
func (di *WindowDelegate) HasWindowShouldZoomToFrame() bool {
	return di._WindowShouldZoomToFrame != nil
}

// Asks the delegate whether the specified window should zoom to the specified frame. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419533-windowshouldzoom?language=objc
func (di *WindowDelegate) SetWindowShouldZoomToFrame(f func(window Window, newFrame foundation.Rect) bool) {
	di._WindowShouldZoomToFrame = f
}

// Asks the delegate whether the specified window should zoom to the specified frame. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419533-windowshouldzoom?language=objc
func (di *WindowDelegate) WindowShouldZoomToFrame(window Window, newFrame foundation.Rect) bool {
	return di._WindowShouldZoomToFrame(window, newFrame)
}
func (di *WindowDelegate) HasWindowDidBecomeMain() bool {
	return di._WindowDidBecomeMain != nil
}

// Tells the delegate that the window has become main. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419190-windowdidbecomemain?language=objc
func (di *WindowDelegate) SetWindowDidBecomeMain(f func(notification foundation.Notification)) {
	di._WindowDidBecomeMain = f
}

// Tells the delegate that the window has become main. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419190-windowdidbecomemain?language=objc
func (di *WindowDelegate) WindowDidBecomeMain(notification foundation.Notification) {
	di._WindowDidBecomeMain(notification)
}
func (di *WindowDelegate) HasWindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration() bool {
	return di._WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration != nil
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419709-window?language=objc
func (di *WindowDelegate) SetWindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(f func(window Window, screen Screen, duration foundation.TimeInterval)) {
	di._WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration = f
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419709-window?language=objc
func (di *WindowDelegate) WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(window Window, screen Screen, duration foundation.TimeInterval) {
	di._WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(window, screen, duration)
}
func (di *WindowDelegate) HasWindowShouldDragDocumentWithEventFromWithPasteboard() bool {
	return di._WindowShouldDragDocumentWithEventFromWithPasteboard != nil
}

// Asks the delegate whether a user can drag the document icon from the window’s title bar. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419452-window?language=objc
func (di *WindowDelegate) SetWindowShouldDragDocumentWithEventFromWithPasteboard(f func(window Window, event Event, dragImageLocation foundation.Point, pasteboard Pasteboard) bool) {
	di._WindowShouldDragDocumentWithEventFromWithPasteboard = f
}

// Asks the delegate whether a user can drag the document icon from the window’s title bar. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419452-window?language=objc
func (di *WindowDelegate) WindowShouldDragDocumentWithEventFromWithPasteboard(window Window, event Event, dragImageLocation foundation.Point, pasteboard Pasteboard) bool {
	return di._WindowShouldDragDocumentWithEventFromWithPasteboard(window, event, dragImageLocation, pasteboard)
}
func (di *WindowDelegate) HasWindowDidDecodeRestorableState() bool {
	return di._WindowDidDecodeRestorableState != nil
}

// Tells the delegate the window is has extracted its restorable state from a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419475-window?language=objc
func (di *WindowDelegate) SetWindowDidDecodeRestorableState(f func(window Window, state foundation.Coder)) {
	di._WindowDidDecodeRestorableState = f
}

// Tells the delegate the window is has extracted its restorable state from a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419475-window?language=objc
func (di *WindowDelegate) WindowDidDecodeRestorableState(window Window, state foundation.Coder) {
	di._WindowDidDecodeRestorableState(window, state)
}
func (di *WindowDelegate) HasWindowWillPositionSheetUsingRect() bool {
	return di._WindowWillPositionSheetUsingRect != nil
}

// Tells the delegate that the window is about to show a sheet at the specified location, giving it the opportunity to return a custom location for the attachment of the sheet to the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419611-window?language=objc
func (di *WindowDelegate) SetWindowWillPositionSheetUsingRect(f func(window Window, sheet Window, rect foundation.Rect) foundation.Rect) {
	di._WindowWillPositionSheetUsingRect = f
}

// Tells the delegate that the window is about to show a sheet at the specified location, giving it the opportunity to return a custom location for the attachment of the sheet to the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419611-window?language=objc
func (di *WindowDelegate) WindowWillPositionSheetUsingRect(window Window, sheet Window, rect foundation.Rect) foundation.Rect {
	return di._WindowWillPositionSheetUsingRect(window, sheet, rect)
}
func (di *WindowDelegate) HasWindowDidChangeBackingProperties() bool {
	return di._WindowDidChangeBackingProperties != nil
}

// Tells the delegate that the window backing properties changed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419517-windowdidchangebackingproperties?language=objc
func (di *WindowDelegate) SetWindowDidChangeBackingProperties(f func(notification foundation.Notification)) {
	di._WindowDidChangeBackingProperties = f
}

// Tells the delegate that the window backing properties changed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419517-windowdidchangebackingproperties?language=objc
func (di *WindowDelegate) WindowDidChangeBackingProperties(notification foundation.Notification) {
	di._WindowDidChangeBackingProperties(notification)
}
func (di *WindowDelegate) HasCustomWindowsToEnterFullScreenForWindow() bool {
	return di._CustomWindowsToEnterFullScreenForWindow != nil
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419521-customwindowstoenterfullscreenfo?language=objc
func (di *WindowDelegate) SetCustomWindowsToEnterFullScreenForWindow(f func(window Window) []Window) {
	di._CustomWindowsToEnterFullScreenForWindow = f
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419521-customwindowstoenterfullscreenfo?language=objc
func (di *WindowDelegate) CustomWindowsToEnterFullScreenForWindow(window Window) []Window {
	return di._CustomWindowsToEnterFullScreenForWindow(window)
}
func (di *WindowDelegate) HasWindowWillUseStandardFrameDefaultFrame() bool {
	return di._WindowWillUseStandardFrameDefaultFrame != nil
}

// Called by NSWindow’s [appkit/nswindow/zoom] method while determining the frame a window may be zoomed to. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419684-windowwillusestandardframe?language=objc
func (di *WindowDelegate) SetWindowWillUseStandardFrameDefaultFrame(f func(window Window, newFrame foundation.Rect) foundation.Rect) {
	di._WindowWillUseStandardFrameDefaultFrame = f
}

// Called by NSWindow’s [appkit/nswindow/zoom] method while determining the frame a window may be zoomed to. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419684-windowwillusestandardframe?language=objc
func (di *WindowDelegate) WindowWillUseStandardFrameDefaultFrame(window Window, newFrame foundation.Rect) foundation.Rect {
	return di._WindowWillUseStandardFrameDefaultFrame(window, newFrame)
}
func (di *WindowDelegate) HasWindowDidEnterVersionBrowser() bool {
	return di._WindowDidEnterVersionBrowser != nil
}

// Tells the delegate that the window has entered version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419064-windowdidenterversionbrowser?language=objc
func (di *WindowDelegate) SetWindowDidEnterVersionBrowser(f func(notification foundation.Notification)) {
	di._WindowDidEnterVersionBrowser = f
}

// Tells the delegate that the window has entered version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419064-windowdidenterversionbrowser?language=objc
func (di *WindowDelegate) WindowDidEnterVersionBrowser(notification foundation.Notification) {
	di._WindowDidEnterVersionBrowser(notification)
}
func (di *WindowDelegate) HasWindowStartCustomAnimationToEnterFullScreenWithDuration() bool {
	return di._WindowStartCustomAnimationToEnterFullScreenWithDuration != nil
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419406-window?language=objc
func (di *WindowDelegate) SetWindowStartCustomAnimationToEnterFullScreenWithDuration(f func(window Window, duration foundation.TimeInterval)) {
	di._WindowStartCustomAnimationToEnterFullScreenWithDuration = f
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419406-window?language=objc
func (di *WindowDelegate) WindowStartCustomAnimationToEnterFullScreenWithDuration(window Window, duration foundation.TimeInterval) {
	di._WindowStartCustomAnimationToEnterFullScreenWithDuration(window, duration)
}
func (di *WindowDelegate) HasWindowDidResignMain() bool {
	return di._WindowDidResignMain != nil
}

// Tells the delegate that the window has resigned main window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419584-windowdidresignmain?language=objc
func (di *WindowDelegate) SetWindowDidResignMain(f func(notification foundation.Notification)) {
	di._WindowDidResignMain = f
}

// Tells the delegate that the window has resigned main window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419584-windowdidresignmain?language=objc
func (di *WindowDelegate) WindowDidResignMain(notification foundation.Notification) {
	di._WindowDidResignMain(notification)
}
func (di *WindowDelegate) HasWindowDidExitVersionBrowser() bool {
	return di._WindowDidExitVersionBrowser != nil
}

// Tells the delegate that the window has left version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419501-windowdidexitversionbrowser?language=objc
func (di *WindowDelegate) SetWindowDidExitVersionBrowser(f func(notification foundation.Notification)) {
	di._WindowDidExitVersionBrowser = f
}

// Tells the delegate that the window has left version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419501-windowdidexitversionbrowser?language=objc
func (di *WindowDelegate) WindowDidExitVersionBrowser(notification foundation.Notification) {
	di._WindowDidExitVersionBrowser(notification)
}
func (di *WindowDelegate) HasWindowWillClose() bool {
	return di._WindowWillClose != nil
}

// Tells the delegate that the window is about to close. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419605-windowwillclose?language=objc
func (di *WindowDelegate) SetWindowWillClose(f func(notification foundation.Notification)) {
	di._WindowWillClose = f
}

// Tells the delegate that the window is about to close. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419605-windowwillclose?language=objc
func (di *WindowDelegate) WindowWillClose(notification foundation.Notification) {
	di._WindowWillClose(notification)
}
func (di *WindowDelegate) HasCustomWindowsToExitFullScreenForWindow() bool {
	return di._CustomWindowsToExitFullScreenForWindow != nil
}

// Called when the window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419070-customwindowstoexitfullscreenfor?language=objc
func (di *WindowDelegate) SetCustomWindowsToExitFullScreenForWindow(f func(window Window) []Window) {
	di._CustomWindowsToExitFullScreenForWindow = f
}

// Called when the window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419070-customwindowstoexitfullscreenfor?language=objc
func (di *WindowDelegate) CustomWindowsToExitFullScreenForWindow(window Window) []Window {
	return di._CustomWindowsToExitFullScreenForWindow(window)
}
func (di *WindowDelegate) HasWindowDidUpdate() bool {
	return di._WindowDidUpdate != nil
}

// Tells the delegate that the window received an [appkit/nswindow/update] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419493-windowdidupdate?language=objc
func (di *WindowDelegate) SetWindowDidUpdate(f func(notification foundation.Notification)) {
	di._WindowDidUpdate = f
}

// Tells the delegate that the window received an [appkit/nswindow/update] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419493-windowdidupdate?language=objc
func (di *WindowDelegate) WindowDidUpdate(notification foundation.Notification) {
	di._WindowDidUpdate(notification)
}
func (di *WindowDelegate) HasWindowWillStartLiveResize() bool {
	return di._WindowWillStartLiveResize != nil
}

// Tells the delegate that the window is about to be live resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419555-windowwillstartliveresize?language=objc
func (di *WindowDelegate) SetWindowWillStartLiveResize(f func(notification foundation.Notification)) {
	di._WindowWillStartLiveResize = f
}

// Tells the delegate that the window is about to be live resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419555-windowwillstartliveresize?language=objc
func (di *WindowDelegate) WindowWillStartLiveResize(notification foundation.Notification) {
	di._WindowWillStartLiveResize(notification)
}
func (di *WindowDelegate) HasWindowDidChangeOcclusionState() bool {
	return di._WindowDidChangeOcclusionState != nil
}

// Tells the delegate that the window changed its occlusion state. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419424-windowdidchangeocclusionstate?language=objc
func (di *WindowDelegate) SetWindowDidChangeOcclusionState(f func(notification foundation.Notification)) {
	di._WindowDidChangeOcclusionState = f
}

// Tells the delegate that the window changed its occlusion state. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419424-windowdidchangeocclusionstate?language=objc
func (di *WindowDelegate) WindowDidChangeOcclusionState(notification foundation.Notification) {
	di._WindowDidChangeOcclusionState(notification)
}
func (di *WindowDelegate) HasWindowDidFailToExitFullScreen() bool {
	return di._WindowDidFailToExitFullScreen != nil
}

// Called if the window failed to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419573-windowdidfailtoexitfullscreen?language=objc
func (di *WindowDelegate) SetWindowDidFailToExitFullScreen(f func(window Window)) {
	di._WindowDidFailToExitFullScreen = f
}

// Called if the window failed to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419573-windowdidfailtoexitfullscreen?language=objc
func (di *WindowDelegate) WindowDidFailToExitFullScreen(window Window) {
	di._WindowDidFailToExitFullScreen(window)
}
func (di *WindowDelegate) HasWindowDidExitFullScreen() bool {
	return di._WindowDidExitFullScreen != nil
}

// The window has left full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419146-windowdidexitfullscreen?language=objc
func (di *WindowDelegate) SetWindowDidExitFullScreen(f func(notification foundation.Notification)) {
	di._WindowDidExitFullScreen = f
}

// The window has left full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419146-windowdidexitfullscreen?language=objc
func (di *WindowDelegate) WindowDidExitFullScreen(notification foundation.Notification) {
	di._WindowDidExitFullScreen(notification)
}
func (di *WindowDelegate) HasWindowWillEnterVersionBrowser() bool {
	return di._WindowWillEnterVersionBrowser != nil
}

// Tells the delegate the window is about to enter version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419463-windowwillenterversionbrowser?language=objc
func (di *WindowDelegate) SetWindowWillEnterVersionBrowser(f func(notification foundation.Notification)) {
	di._WindowWillEnterVersionBrowser = f
}

// Tells the delegate the window is about to enter version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419463-windowwillenterversionbrowser?language=objc
func (di *WindowDelegate) WindowWillEnterVersionBrowser(notification foundation.Notification) {
	di._WindowWillEnterVersionBrowser(notification)
}

// ensure impl type implements protocol interface
var _ PWindowDelegate = (*WindowDelegateObject)(nil)

// A concrete type for the [PWindowDelegate] protocol.
type WindowDelegateObject struct {
	objc.Object
}

func (w_ WindowDelegateObject) HasWindowWillUseFullScreenContentSize() bool {
	return w_.RespondsToSelector(objc.Sel("window:willUseFullScreenContentSize:"))
}

// Called to allow the delegate to modify the full-screen content size. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419282-window?language=objc
func (w_ WindowDelegateObject) WindowWillUseFullScreenContentSize(window Window, proposedSize foundation.Size) foundation.Size {
	rv := objc.Call[foundation.Size](w_, objc.Sel("window:willUseFullScreenContentSize:"), window, proposedSize)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidMove() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidMove:"))
}

// Tells the delegate that the window has moved. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419674-windowdidmove?language=objc
func (w_ WindowDelegateObject) WindowDidMove(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidMove:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidDeminiaturize() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidDeminiaturize:"))
}

// Tells the delegate that the window has been deminimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419296-windowdiddeminiaturize?language=objc
func (w_ WindowDelegateObject) WindowDidDeminiaturize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidDeminiaturize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidChangeScreenProfile() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidChangeScreenProfile:"))
}

// Tells the delegate that the window has changed screen display profiles. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419581-windowdidchangescreenprofile?language=objc
func (w_ WindowDelegateObject) WindowDidChangeScreenProfile(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidChangeScreenProfile:"), notification)
}

func (w_ WindowDelegateObject) HasCustomWindowsToEnterFullScreenForWindowOnScreen() bool {
	return w_.RespondsToSelector(objc.Sel("customWindowsToEnterFullScreenForWindow:onScreen:"))
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419557-customwindowstoenterfullscreenfo?language=objc
func (w_ WindowDelegateObject) CustomWindowsToEnterFullScreenForWindowOnScreen(window Window, screen Screen) []Window {
	rv := objc.Call[[]Window](w_, objc.Sel("customWindowsToEnterFullScreenForWindow:onScreen:"), window, screen)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidChangeScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidChangeScreen:"))
}

// Tells the delegate that the window has changed screens. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419267-windowdidchangescreen?language=objc
func (w_ WindowDelegateObject) WindowDidChangeScreen(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidChangeScreen:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillUseFullScreenPresentationOptions() bool {
	return w_.RespondsToSelector(objc.Sel("window:willUseFullScreenPresentationOptions:"))
}

// Returns the presentation options the window uses when transitioning to full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419144-window?language=objc
func (w_ WindowDelegateObject) WindowWillUseFullScreenPresentationOptions(window Window, proposedOptions ApplicationPresentationOptions) ApplicationPresentationOptions {
	rv := objc.Call[ApplicationPresentationOptions](w_, objc.Sel("window:willUseFullScreenPresentationOptions:"), window, proposedOptions)
	return rv
}

func (w_ WindowDelegateObject) HasWindowWillBeginSheet() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillBeginSheet:"))
}

// Notifies the delegate that the window is about to open a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419408-windowwillbeginsheet?language=objc
func (w_ WindowDelegateObject) WindowWillBeginSheet(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillBeginSheet:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillReturnFieldEditorToObject() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillReturnFieldEditor:toObject:"))
}

// Tells the delegate that the field editor for a text-displaying object has been requested. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419416-windowwillreturnfieldeditor?language=objc
func (w_ WindowDelegateObject) WindowWillReturnFieldEditorToObject(sender Window, client objc.Object) objc.Object {
	rv := objc.Call[objc.Object](w_, objc.Sel("windowWillReturnFieldEditor:toObject:"), sender, client)
	return rv
}

func (w_ WindowDelegateObject) HasWindowShouldClose() bool {
	return w_.RespondsToSelector(objc.Sel("windowShouldClose:"))
}

// Tells the delegate that the user has attempted to close a window or the window has received a [appkit/nswindow/performclose] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419380-windowshouldclose?language=objc
func (w_ WindowDelegateObject) WindowShouldClose(sender Window) bool {
	rv := objc.Call[bool](w_, objc.Sel("windowShouldClose:"), sender)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidResignKey() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidResignKey:"))
}

// Tells the delegate that the window has resigned key window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419711-windowdidresignkey?language=objc
func (w_ WindowDelegateObject) WindowDidResignKey(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidResignKey:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidEndSheet() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidEndSheet:"))
}

// Tells the delegate that the window has closed a sheet. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419773-windowdidendsheet?language=objc
func (w_ WindowDelegateObject) WindowDidEndSheet(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidEndSheet:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidBecomeKey() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidBecomeKey:"))
}

// Tells the delegate that the window has become the key window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419737-windowdidbecomekey?language=objc
func (w_ WindowDelegateObject) WindowDidBecomeKey(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidBecomeKey:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillResizeToSize() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillResize:toSize:"))
}

// Tells the delegate that the window is being resized (whether by the user or through one of the setFrame... methods other than [appkit/nswindow/setframe]). [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419292-windowwillresize?language=objc
func (w_ WindowDelegateObject) WindowWillResizeToSize(sender Window, frameSize foundation.Size) foundation.Size {
	rv := objc.Call[foundation.Size](w_, objc.Sel("windowWillResize:toSize:"), sender, frameSize)
	return rv
}

func (w_ WindowDelegateObject) HasWindowWillMiniaturize() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillMiniaturize:"))
}

// Tells the delegate that the window is about to be minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419461-windowwillminiaturize?language=objc
func (w_ WindowDelegateObject) WindowWillMiniaturize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillMiniaturize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillEncodeRestorableState() bool {
	return w_.RespondsToSelector(objc.Sel("window:willEncodeRestorableState:"))
}

// Tells the delegate the window is about to add its restorable state to a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419619-window?language=objc
func (w_ WindowDelegateObject) WindowWillEncodeRestorableState(window Window, state foundation.Coder) {
	objc.Call[objc.Void](w_, objc.Sel("window:willEncodeRestorableState:"), window, state)
}

func (w_ WindowDelegateObject) HasWindowWillExitVersionBrowser() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillExitVersionBrowser:"))
}

// Tells the delegate that the window is about to leave version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419252-windowwillexitversionbrowser?language=objc
func (w_ WindowDelegateObject) WindowWillExitVersionBrowser(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillExitVersionBrowser:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidEnterFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidEnterFullScreen:"))
}

// The window has entered full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419116-windowdidenterfullscreen?language=objc
func (w_ WindowDelegateObject) WindowDidEnterFullScreen(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidEnterFullScreen:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidResize() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidResize:"))
}

// Tells the delegate that the window has been resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419567-windowdidresize?language=objc
func (w_ WindowDelegateObject) WindowDidResize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidResize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillMove() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillMove:"))
}

// Tells the delegate that the window is about to move. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419336-windowwillmove?language=objc
func (w_ WindowDelegateObject) WindowWillMove(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillMove:"), notification)
}

func (w_ WindowDelegateObject) HasWindowStartCustomAnimationToExitFullScreenWithDuration() bool {
	return w_.RespondsToSelector(objc.Sel("window:startCustomAnimationToExitFullScreenWithDuration:"))
}

// This method is called to start the window animation out of full-screen mode, including transitioning back to the desktop space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419705-window?language=objc
func (w_ WindowDelegateObject) WindowStartCustomAnimationToExitFullScreenWithDuration(window Window, duration foundation.TimeInterval) {
	objc.Call[objc.Void](w_, objc.Sel("window:startCustomAnimationToExitFullScreenWithDuration:"), window, duration)
}

func (w_ WindowDelegateObject) HasWindowWillExitFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillExitFullScreen:"))
}

// The window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419332-windowwillexitfullscreen?language=objc
func (w_ WindowDelegateObject) WindowWillExitFullScreen(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillExitFullScreen:"), notification)
}

func (w_ WindowDelegateObject) HasWindowShouldPopUpDocumentPathMenu() bool {
	return w_.RespondsToSelector(objc.Sel("window:shouldPopUpDocumentPathMenu:"))
}

// Asks the delegate whether the window displays the title pop-up menu in response to a Command-click or Control-click on its title. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419465-window?language=objc
func (w_ WindowDelegateObject) WindowShouldPopUpDocumentPathMenu(window Window, menu Menu) bool {
	rv := objc.Call[bool](w_, objc.Sel("window:shouldPopUpDocumentPathMenu:"), window, menu)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidMiniaturize() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidMiniaturize:"))
}

// Tells the delegate that the window has been minimized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419621-windowdidminiaturize?language=objc
func (w_ WindowDelegateObject) WindowDidMiniaturize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidMiniaturize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillReturnUndoManager() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillReturnUndoManager:"))
}

// Tells the delegate that the window’s undo manager has been requested. Returns the appropriate undo manager for the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419745-windowwillreturnundomanager?language=objc
func (w_ WindowDelegateObject) WindowWillReturnUndoManager(window Window) foundation.UndoManager {
	rv := objc.Call[foundation.UndoManager](w_, objc.Sel("windowWillReturnUndoManager:"), window)
	return rv
}

func (w_ WindowDelegateObject) HasWindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize() bool {
	return w_.RespondsToSelector(objc.Sel("window:willResizeForVersionBrowserWithMaxPreferredSize:maxAllowedSize:"))
}

// Tells the delegate the window will resize for presentation during version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419360-window?language=objc
func (w_ WindowDelegateObject) WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(window Window, maxPreferredFrameSize foundation.Size, maxAllowedFrameSize foundation.Size) foundation.Size {
	rv := objc.Call[foundation.Size](w_, objc.Sel("window:willResizeForVersionBrowserWithMaxPreferredSize:maxAllowedSize:"), window, maxPreferredFrameSize, maxAllowedFrameSize)
	return rv
}

func (w_ WindowDelegateObject) HasWindowWillEnterFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillEnterFullScreen:"))
}

// The window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419563-windowwillenterfullscreen?language=objc
func (w_ WindowDelegateObject) WindowWillEnterFullScreen(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillEnterFullScreen:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidFailToEnterFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidFailToEnterFullScreen:"))
}

// Called if the window failed to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419591-windowdidfailtoenterfullscreen?language=objc
func (w_ WindowDelegateObject) WindowDidFailToEnterFullScreen(window Window) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidFailToEnterFullScreen:"), window)
}

func (w_ WindowDelegateObject) HasWindowDidExpose() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidExpose:"))
}

// Tells the delegate that the window has been exposed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419258-windowdidexpose?language=objc
func (w_ WindowDelegateObject) WindowDidExpose(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidExpose:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidEndLiveResize() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidEndLiveResize:"))
}

// Tells the delegate that a live resize operation on the window has ended. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419150-windowdidendliveresize?language=objc
func (w_ WindowDelegateObject) WindowDidEndLiveResize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidEndLiveResize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowShouldZoomToFrame() bool {
	return w_.RespondsToSelector(objc.Sel("windowShouldZoom:toFrame:"))
}

// Asks the delegate whether the specified window should zoom to the specified frame. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419533-windowshouldzoom?language=objc
func (w_ WindowDelegateObject) WindowShouldZoomToFrame(window Window, newFrame foundation.Rect) bool {
	rv := objc.Call[bool](w_, objc.Sel("windowShouldZoom:toFrame:"), window, newFrame)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidBecomeMain() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidBecomeMain:"))
}

// Tells the delegate that the window has become main. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419190-windowdidbecomemain?language=objc
func (w_ WindowDelegateObject) WindowDidBecomeMain(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidBecomeMain:"), notification)
}

func (w_ WindowDelegateObject) HasWindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration() bool {
	return w_.RespondsToSelector(objc.Sel("window:startCustomAnimationToEnterFullScreenOnScreen:withDuration:"))
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419709-window?language=objc
func (w_ WindowDelegateObject) WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(window Window, screen Screen, duration foundation.TimeInterval) {
	objc.Call[objc.Void](w_, objc.Sel("window:startCustomAnimationToEnterFullScreenOnScreen:withDuration:"), window, screen, duration)
}

func (w_ WindowDelegateObject) HasWindowShouldDragDocumentWithEventFromWithPasteboard() bool {
	return w_.RespondsToSelector(objc.Sel("window:shouldDragDocumentWithEvent:from:withPasteboard:"))
}

// Asks the delegate whether a user can drag the document icon from the window’s title bar. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419452-window?language=objc
func (w_ WindowDelegateObject) WindowShouldDragDocumentWithEventFromWithPasteboard(window Window, event Event, dragImageLocation foundation.Point, pasteboard Pasteboard) bool {
	rv := objc.Call[bool](w_, objc.Sel("window:shouldDragDocumentWithEvent:from:withPasteboard:"), window, event, dragImageLocation, pasteboard)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidDecodeRestorableState() bool {
	return w_.RespondsToSelector(objc.Sel("window:didDecodeRestorableState:"))
}

// Tells the delegate the window is has extracted its restorable state from a given archiver. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419475-window?language=objc
func (w_ WindowDelegateObject) WindowDidDecodeRestorableState(window Window, state foundation.Coder) {
	objc.Call[objc.Void](w_, objc.Sel("window:didDecodeRestorableState:"), window, state)
}

func (w_ WindowDelegateObject) HasWindowWillPositionSheetUsingRect() bool {
	return w_.RespondsToSelector(objc.Sel("window:willPositionSheet:usingRect:"))
}

// Tells the delegate that the window is about to show a sheet at the specified location, giving it the opportunity to return a custom location for the attachment of the sheet to the window. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419611-window?language=objc
func (w_ WindowDelegateObject) WindowWillPositionSheetUsingRect(window Window, sheet Window, rect foundation.Rect) foundation.Rect {
	rv := objc.Call[foundation.Rect](w_, objc.Sel("window:willPositionSheet:usingRect:"), window, sheet, rect)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidChangeBackingProperties() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidChangeBackingProperties:"))
}

// Tells the delegate that the window backing properties changed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419517-windowdidchangebackingproperties?language=objc
func (w_ WindowDelegateObject) WindowDidChangeBackingProperties(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidChangeBackingProperties:"), notification)
}

func (w_ WindowDelegateObject) HasCustomWindowsToEnterFullScreenForWindow() bool {
	return w_.RespondsToSelector(objc.Sel("customWindowsToEnterFullScreenForWindow:"))
}

// Called when the window is about to enter full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419521-customwindowstoenterfullscreenfo?language=objc
func (w_ WindowDelegateObject) CustomWindowsToEnterFullScreenForWindow(window Window) []Window {
	rv := objc.Call[[]Window](w_, objc.Sel("customWindowsToEnterFullScreenForWindow:"), window)
	return rv
}

func (w_ WindowDelegateObject) HasWindowWillUseStandardFrameDefaultFrame() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillUseStandardFrame:defaultFrame:"))
}

// Called by NSWindow’s [appkit/nswindow/zoom] method while determining the frame a window may be zoomed to. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419684-windowwillusestandardframe?language=objc
func (w_ WindowDelegateObject) WindowWillUseStandardFrameDefaultFrame(window Window, newFrame foundation.Rect) foundation.Rect {
	rv := objc.Call[foundation.Rect](w_, objc.Sel("windowWillUseStandardFrame:defaultFrame:"), window, newFrame)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidEnterVersionBrowser() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidEnterVersionBrowser:"))
}

// Tells the delegate that the window has entered version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419064-windowdidenterversionbrowser?language=objc
func (w_ WindowDelegateObject) WindowDidEnterVersionBrowser(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidEnterVersionBrowser:"), notification)
}

func (w_ WindowDelegateObject) HasWindowStartCustomAnimationToEnterFullScreenWithDuration() bool {
	return w_.RespondsToSelector(objc.Sel("window:startCustomAnimationToEnterFullScreenWithDuration:"))
}

// This method is called to start the window animation into full-screen mode, including transitioning to a new space. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419406-window?language=objc
func (w_ WindowDelegateObject) WindowStartCustomAnimationToEnterFullScreenWithDuration(window Window, duration foundation.TimeInterval) {
	objc.Call[objc.Void](w_, objc.Sel("window:startCustomAnimationToEnterFullScreenWithDuration:"), window, duration)
}

func (w_ WindowDelegateObject) HasWindowDidResignMain() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidResignMain:"))
}

// Tells the delegate that the window has resigned main window status. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419584-windowdidresignmain?language=objc
func (w_ WindowDelegateObject) WindowDidResignMain(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidResignMain:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidExitVersionBrowser() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidExitVersionBrowser:"))
}

// Tells the delegate that the window has left version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419501-windowdidexitversionbrowser?language=objc
func (w_ WindowDelegateObject) WindowDidExitVersionBrowser(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidExitVersionBrowser:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillClose() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillClose:"))
}

// Tells the delegate that the window is about to close. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419605-windowwillclose?language=objc
func (w_ WindowDelegateObject) WindowWillClose(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillClose:"), notification)
}

func (w_ WindowDelegateObject) HasCustomWindowsToExitFullScreenForWindow() bool {
	return w_.RespondsToSelector(objc.Sel("customWindowsToExitFullScreenForWindow:"))
}

// Called when the window is about to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419070-customwindowstoexitfullscreenfor?language=objc
func (w_ WindowDelegateObject) CustomWindowsToExitFullScreenForWindow(window Window) []Window {
	rv := objc.Call[[]Window](w_, objc.Sel("customWindowsToExitFullScreenForWindow:"), window)
	return rv
}

func (w_ WindowDelegateObject) HasWindowDidUpdate() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidUpdate:"))
}

// Tells the delegate that the window received an [appkit/nswindow/update] message. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419493-windowdidupdate?language=objc
func (w_ WindowDelegateObject) WindowDidUpdate(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidUpdate:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillStartLiveResize() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillStartLiveResize:"))
}

// Tells the delegate that the window is about to be live resized. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419555-windowwillstartliveresize?language=objc
func (w_ WindowDelegateObject) WindowWillStartLiveResize(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillStartLiveResize:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidChangeOcclusionState() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidChangeOcclusionState:"))
}

// Tells the delegate that the window changed its occlusion state. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419424-windowdidchangeocclusionstate?language=objc
func (w_ WindowDelegateObject) WindowDidChangeOcclusionState(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidChangeOcclusionState:"), notification)
}

func (w_ WindowDelegateObject) HasWindowDidFailToExitFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidFailToExitFullScreen:"))
}

// Called if the window failed to exit full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419573-windowdidfailtoexitfullscreen?language=objc
func (w_ WindowDelegateObject) WindowDidFailToExitFullScreen(window Window) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidFailToExitFullScreen:"), window)
}

func (w_ WindowDelegateObject) HasWindowDidExitFullScreen() bool {
	return w_.RespondsToSelector(objc.Sel("windowDidExitFullScreen:"))
}

// The window has left full-screen mode. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419146-windowdidexitfullscreen?language=objc
func (w_ WindowDelegateObject) WindowDidExitFullScreen(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowDidExitFullScreen:"), notification)
}

func (w_ WindowDelegateObject) HasWindowWillEnterVersionBrowser() bool {
	return w_.RespondsToSelector(objc.Sel("windowWillEnterVersionBrowser:"))
}

// Tells the delegate the window is about to enter version browsing. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419463-windowwillenterversionbrowser?language=objc
func (w_ WindowDelegateObject) WindowWillEnterVersionBrowser(notification foundation.Notification) {
	objc.Call[objc.Void](w_, objc.Sel("windowWillEnterVersionBrowser:"), notification)
}
