// Code generated by darwinkit-gen. DO NOT EDIT.

package speech

// SFSpeechRecognizerAuthorizationStatus represents the authorization status for speech recognition
type SFSpeechRecognizerAuthorizationStatus int

const (
	SFSpeechRecognizerAuthorizationStatusNotDetermined SFSpeechRecognizerAuthorizationStatus = 0
	SFSpeechRecognizerAuthorizationStatusDenied       SFSpeechRecognizerAuthorizationStatus = 1
	SFSpeechRecognizerAuthorizationStatusRestricted   SFSpeechRecognizerAuthorizationStatus = 2
	SFSpeechRecognizerAuthorizationStatusAuthorized   SFSpeechRecognizerAuthorizationStatus = 3
)

// SFSpeechRecognitionTaskState represents the state of a speech recognition task
type SFSpeechRecognitionTaskState int

const (
	SFSpeechRecognitionTaskStateStarting    SFSpeechRecognitionTaskState = 0
	SFSpeechRecognitionTaskStateRunning     SFSpeechRecognitionTaskState = 1
	SFSpeechRecognitionTaskStateFinishing   SFSpeechRecognitionTaskState = 2
	SFSpeechRecognitionTaskStateCompleted   SFSpeechRecognitionTaskState = 3
	SFSpeechRecognitionTaskStateCanceling   SFSpeechRecognitionTaskState = 4
	SFSpeechRecognitionTaskStateCancelled   SFSpeechRecognitionTaskState = 5
)

// SFSpeechRecognitionResult represents a speech recognition result
type SFSpeechRecognitionResult struct {
	BestTranscription string
	IsFinal          bool
	Confidence       float64
}

// SFVoiceQuality represents the quality of a voice
type SFVoiceQuality int

const (
	SFVoiceQualityDefault    SFVoiceQuality = 1
	SFVoiceQualityPremium    SFVoiceQuality = 2
)

// SFVoiceGender represents the gender of a voice
type SFVoiceGender int

const (
	SFVoiceGenderUnspecified SFVoiceGender = 0
	SFVoiceGenderFemale      SFVoiceGender = 1
	SFVoiceGenderMale        SFVoiceGender = 2
)

// SFTranscriptionSegmentConfidence represents the confidence level of a transcription segment
type SFTranscriptionSegmentConfidence int

const (
	SFTranscriptionSegmentConfidenceLow     SFTranscriptionSegmentConfidence = 0
	SFTranscriptionSegmentConfidenceMedium  SFTranscriptionSegmentConfidence = 1
	SFTranscriptionSegmentConfidenceHigh    SFTranscriptionSegmentConfidence = 2
)

// SFAcousticFeature represents an acoustic feature
type SFAcousticFeature int

const (
	SFAcousticFeatureVoicing              SFAcousticFeature = 1
	SFAcousticFeatureVoicelessness        SFAcousticFeature = 2
	SFAcousticFeaturePitch                SFAcousticFeature = 3
	SFAcousticFeatureJitter               SFAcousticFeature = 4
	SFAcousticFeatureShimmer              SFAcousticFeature = 5
)

// SFSpeechErrorCode represents an error code for speech recognition
type SFSpeechErrorCode int

const (
	SFSpeechErrorCodeNoError                      SFSpeechErrorCode = 0
	SFSpeechErrorCodeClientNotAuthorized          SFSpeechErrorCode = 1
	SFSpeechErrorCodeClientNotAvailable           SFSpeechErrorCode = 2
	SFSpeechErrorCodeAudioEngineError             SFSpeechErrorCode = 3
	SFSpeechErrorCodeServerError                  SFSpeechErrorCode = 4
	SFSpeechErrorCodeConnectionFailed             SFSpeechErrorCode = 5
	SFSpeechErrorCodeConnectionTimeout            SFSpeechErrorCode = 6
	SFSpeechErrorCodeFailedToActivateService      SFSpeechErrorCode = 7
	SFSpeechErrorCodeRecognitionCancelled         SFSpeechErrorCode = 8
	SFSpeechErrorCodeInvalidRequest               SFSpeechErrorCode = 9
)

// SFVoiceAnalyzerMode represents the mode of voice analysis
type SFVoiceAnalyzerMode int

const (
	SFVoiceAnalyzerModeRealTime    SFVoiceAnalyzerMode = 0
	SFVoiceAnalyzerModeOffline     SFVoiceAnalyzerMode = 1
)

// SFSpeechLanguageModel represents a language model for speech recognition
type SFSpeechLanguageModel int

const (
	SFSpeechLanguageModelGeneral    SFSpeechLanguageModel = 0
	SFSpeechLanguageModelSearch     SFSpeechLanguageModel = 1
	SFSpeechLanguageModelDictation  SFSpeechLanguageModel = 2
)

// SFVocalFeature represents a vocal feature
type SFVocalFeature int

const (
	SFVocalFeatureSpectralEnergy    SFVocalFeature = 0
	SFVocalFeatureVoiceTremor       SFVocalFeature = 1
	SFVocalFeatureVoiceQuality      SFVocalFeature = 2
)