// Code generated by DarwinKit. DO NOT EDIT.

#import "Quartz/Quartz.h"

void importQuartzProtocols() {
    id o;
    o = @protocol(IKCameraDeviceViewDelegate);
    o = @protocol(IKDeviceBrowserViewDelegate);
    o = @protocol(IKFilterCustomUIProvider);
    o = @protocol(IKImageEditPanelDataSource);
    o = @protocol(IKScannerDeviceViewDelegate);
    o = @protocol(IKSlideshowDataSource);
    o = @protocol(QCCompositionRenderer);
    o = @protocol(QCPlugInContext);
    o = @protocol(QCPlugInInputImageSource);
    o = @protocol(QCPlugInOutputImageProvider);
}
