// Code generated by DarwinKit. DO NOT EDIT.

package mps

import (
	"github.com/progrium/macdriver/objc"
)

//	[Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/metalperformanceshaders/mpsnnlosscallback?language=objc
type PNNLossCallback interface {
	// optional
	ScalarWeightForSourceImageDestinationImage(sourceImage Image, destinationImage Image) float64
	HasScalarWeightForSourceImageDestinationImage() bool
}

// ensure impl type implements protocol interface
var _ PNNLossCallback = (*NNLossCallbackObject)(nil)

// A concrete type for the [PNNLossCallback] protocol.
type NNLossCallbackObject struct {
	objc.Object
}

func (n_ NNLossCallbackObject) HasScalarWeightForSourceImageDestinationImage() bool {
	return n_.RespondsToSelector(objc.Sel("scalarWeightForSourceImage:destinationImage:"))
}

//	[Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/metalperformanceshaders/mpsnnlosscallback/3131851-scalarweightforsourceimage?language=objc
func (n_ NNLossCallbackObject) ScalarWeightForSourceImageDestinationImage(sourceImage Image, destinationImage Image) float64 {
	rv := objc.Call[float64](n_, objc.Sel("scalarWeightForSourceImage:destinationImage:"), objc.Ptr(sourceImage), objc.Ptr(destinationImage))
	return rv
}
