// Code generated by DarwinKit. DO NOT EDIT.

package coreimage

import (
	"github.com/progrium/darwinkit/objc"
)

//	[Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/ciareaminimum?language=objc
type PAreaMinimum interface {
}

// ensure impl type implements protocol interface
var _ PAreaMinimum = (*AreaMinimumObject)(nil)

// A concrete type for the [PAreaMinimum] protocol.
type AreaMinimumObject struct {
	objc.Object
}
