// Code generated by DarwinKit. DO NOT EDIT.

package coreimage

import (
	"github.com/progrium/darwinkit/macos/coregraphics"
	"github.com/progrium/darwinkit/objc"
)

// The properties you use to configure a circular screen filter. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen?language=objc
type PCircularScreen interface {
	// optional
	SetWidth(value float32)
	HasSetWidth() bool

	// optional
	Width() float32
	HasWidth() bool

	// optional
	SetCenter(value coregraphics.Point)
	HasSetCenter() bool

	// optional
	Center() coregraphics.Point
	HasCenter() bool

	// optional
	SetInputImage(value Image)
	HasSetInputImage() bool

	// optional
	InputImage() Image
	HasInputImage() bool

	// optional
	SetSharpness(value float32)
	HasSetSharpness() bool

	// optional
	Sharpness() float32
	HasSharpness() bool
}

// ensure impl type implements protocol interface
var _ PCircularScreen = (*CircularScreenObject)(nil)

// A concrete type for the [PCircularScreen] protocol.
type CircularScreenObject struct {
	objc.Object
}

func (c_ CircularScreenObject) HasSetWidth() bool {
	return c_.RespondsToSelector(objc.Sel("setWidth:"))
}

// The distance between each circle in the pattern. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228114-width?language=objc
func (c_ CircularScreenObject) SetWidth(value float32) {
	objc.Call[objc.Void](c_, objc.Sel("setWidth:"), value)
}

func (c_ CircularScreenObject) HasWidth() bool {
	return c_.RespondsToSelector(objc.Sel("width"))
}

// The distance between each circle in the pattern. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228114-width?language=objc
func (c_ CircularScreenObject) Width() float32 {
	rv := objc.Call[float32](c_, objc.Sel("width"))
	return rv
}

func (c_ CircularScreenObject) HasSetCenter() bool {
	return c_.RespondsToSelector(objc.Sel("setCenter:"))
}

// The x and y position to use as the center of the circular screen pattern. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228111-center?language=objc
func (c_ CircularScreenObject) SetCenter(value coregraphics.Point) {
	objc.Call[objc.Void](c_, objc.Sel("setCenter:"), value)
}

func (c_ CircularScreenObject) HasCenter() bool {
	return c_.RespondsToSelector(objc.Sel("center"))
}

// The x and y position to use as the center of the circular screen pattern. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228111-center?language=objc
func (c_ CircularScreenObject) Center() coregraphics.Point {
	rv := objc.Call[coregraphics.Point](c_, objc.Sel("center"))
	return rv
}

func (c_ CircularScreenObject) HasSetInputImage() bool {
	return c_.RespondsToSelector(objc.Sel("setInputImage:"))
}

// The image to use as an input image. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228112-inputimage?language=objc
func (c_ CircularScreenObject) SetInputImage(value Image) {
	objc.Call[objc.Void](c_, objc.Sel("setInputImage:"), value)
}

func (c_ CircularScreenObject) HasInputImage() bool {
	return c_.RespondsToSelector(objc.Sel("inputImage"))
}

// The image to use as an input image. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228112-inputimage?language=objc
func (c_ CircularScreenObject) InputImage() Image {
	rv := objc.Call[Image](c_, objc.Sel("inputImage"))
	return rv
}

func (c_ CircularScreenObject) HasSetSharpness() bool {
	return c_.RespondsToSelector(objc.Sel("setSharpness:"))
}

// The sharpness of the circles. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228113-sharpness?language=objc
func (c_ CircularScreenObject) SetSharpness(value float32) {
	objc.Call[objc.Void](c_, objc.Sel("setSharpness:"), value)
}

func (c_ CircularScreenObject) HasSharpness() bool {
	return c_.RespondsToSelector(objc.Sel("sharpness"))
}

// The sharpness of the circles. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cicircularscreen/3228113-sharpness?language=objc
func (c_ CircularScreenObject) Sharpness() float32 {
	rv := objc.Call[float32](c_, objc.Sel("sharpness"))
	return rv
}
