// Code generated by DarwinKit. DO NOT EDIT.

// Use built-in or custom filters to process still and video images.
//
// [Apple Documentation]
//
// [Apple Documentation]: https://developer.apple.com/documentation/coreimage?language=objc
package coreimage
