// Code generated by DarwinKit. DO NOT EDIT.

package coreimage

import (
	"unsafe"

	"github.com/progrium/darwinkit/objc"
)

// The interface for loading Core Image image units. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cipluginregistration?language=objc
type PPlugInRegistration interface {
	// optional
	Load(host unsafe.Pointer) bool
	HasLoad() bool
}

// ensure impl type implements protocol interface
var _ PPlugInRegistration = (*PlugInRegistrationObject)(nil)

// A concrete type for the [PPlugInRegistration] protocol.
type PlugInRegistrationObject struct {
	objc.Object
}

func (p_ PlugInRegistrationObject) HasLoad() bool {
	return p_.RespondsToSelector(objc.Sel("load:"))
}

// Loads and initializes an image unit, performing custom tasks as needed. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/cipluginregistration/1437823-load?language=objc
func (p_ PlugInRegistrationObject) Load(host unsafe.Pointer) bool {
	rv := objc.Call[bool](p_, objc.Sel("load:"), host)
	return rv
}
