// Code generated by DarwinKit. DO NOT EDIT.

package coreimage

import (
	"github.com/progrium/darwinkit/objc"
)

// The properties you use to configure a text image generator filter. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator?language=objc
type PTextImageGenerator interface {
	// optional
	SetFontName(value string)
	HasSetFontName() bool

	// optional
	FontName() string
	HasFontName() bool

	// optional
	SetScaleFactor(value float32)
	HasSetScaleFactor() bool

	// optional
	ScaleFactor() float32
	HasScaleFactor() bool

	// optional
	SetText(value string)
	HasSetText() bool

	// optional
	Text() string
	HasText() bool

	// optional
	SetFontSize(value float32)
	HasSetFontSize() bool

	// optional
	FontSize() float32
	HasFontSize() bool
}

// ensure impl type implements protocol interface
var _ PTextImageGenerator = (*TextImageGeneratorObject)(nil)

// A concrete type for the [PTextImageGenerator] protocol.
type TextImageGeneratorObject struct {
	objc.Object
}

func (t_ TextImageGeneratorObject) HasSetFontName() bool {
	return t_.RespondsToSelector(objc.Sel("setFontName:"))
}

// The name of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228785-fontname?language=objc
func (t_ TextImageGeneratorObject) SetFontName(value string) {
	objc.Call[objc.Void](t_, objc.Sel("setFontName:"), value)
}

func (t_ TextImageGeneratorObject) HasFontName() bool {
	return t_.RespondsToSelector(objc.Sel("fontName"))
}

// The name of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228785-fontname?language=objc
func (t_ TextImageGeneratorObject) FontName() string {
	rv := objc.Call[string](t_, objc.Sel("fontName"))
	return rv
}

func (t_ TextImageGeneratorObject) HasSetScaleFactor() bool {
	return t_.RespondsToSelector(objc.Sel("setScaleFactor:"))
}

// The scale of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228787-scalefactor?language=objc
func (t_ TextImageGeneratorObject) SetScaleFactor(value float32) {
	objc.Call[objc.Void](t_, objc.Sel("setScaleFactor:"), value)
}

func (t_ TextImageGeneratorObject) HasScaleFactor() bool {
	return t_.RespondsToSelector(objc.Sel("scaleFactor"))
}

// The scale of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228787-scalefactor?language=objc
func (t_ TextImageGeneratorObject) ScaleFactor() float32 {
	rv := objc.Call[float32](t_, objc.Sel("scaleFactor"))
	return rv
}

func (t_ TextImageGeneratorObject) HasSetText() bool {
	return t_.RespondsToSelector(objc.Sel("setText:"))
}

// The text to render. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228788-text?language=objc
func (t_ TextImageGeneratorObject) SetText(value string) {
	objc.Call[objc.Void](t_, objc.Sel("setText:"), value)
}

func (t_ TextImageGeneratorObject) HasText() bool {
	return t_.RespondsToSelector(objc.Sel("text"))
}

// The text to render. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228788-text?language=objc
func (t_ TextImageGeneratorObject) Text() string {
	rv := objc.Call[string](t_, objc.Sel("text"))
	return rv
}

func (t_ TextImageGeneratorObject) HasSetFontSize() bool {
	return t_.RespondsToSelector(objc.Sel("setFontSize:"))
}

// The size of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228786-fontsize?language=objc
func (t_ TextImageGeneratorObject) SetFontSize(value float32) {
	objc.Call[objc.Void](t_, objc.Sel("setFontSize:"), value)
}

func (t_ TextImageGeneratorObject) HasFontSize() bool {
	return t_.RespondsToSelector(objc.Sel("fontSize"))
}

// The size of the font to use for the generated text. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/coreimage/citextimagegenerator/3228786-fontsize?language=objc
func (t_ TextImageGeneratorObject) FontSize() float32 {
	rv := objc.Call[float32](t_, objc.Sel("fontSize"))
	return rv
}
