// Code generated by DarwinKit. DO NOT EDIT.

package cloudkit

import (
	"github.com/progrium/darwinkit/objc"
)

// A protocol for managing the key-value pairs of a CloudKit record. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting?language=objc
type PRecordKeyValueSetting interface {
	// optional
	AllKeys() []RecordFieldKey
	HasAllKeys() bool

	// optional
	ChangedKeys() []RecordFieldKey
	HasChangedKeys() bool

	// optional
	ObjectForKeyedSubscript(key RecordFieldKey) RecordValueObject
	HasObjectForKeyedSubscript() bool

	// optional
	SetObjectForKeyedSubscript(object RecordValueObject, key RecordFieldKey)
	HasSetObjectForKeyedSubscript() bool

	// optional
	SetObjectForKey(object RecordValueObject, key RecordFieldKey)
	HasSetObjectForKey() bool

	// optional
	ObjectForKey(key RecordFieldKey) RecordValueObject
	HasObjectForKey() bool
}

// ensure impl type implements protocol interface
var _ PRecordKeyValueSetting = (*RecordKeyValueSettingObject)(nil)

// A concrete type for the [PRecordKeyValueSetting] protocol.
type RecordKeyValueSettingObject struct {
	objc.Object
}

func (r_ RecordKeyValueSettingObject) HasAllKeys() bool {
	return r_.RespondsToSelector(objc.Sel("allKeys"))
}

// Returns an array of the record’s keys. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976183-allkeys?language=objc
func (r_ RecordKeyValueSettingObject) AllKeys() []RecordFieldKey {
	rv := objc.Call[[]RecordFieldKey](r_, objc.Sel("allKeys"))
	return rv
}

func (r_ RecordKeyValueSettingObject) HasChangedKeys() bool {
	return r_.RespondsToSelector(objc.Sel("changedKeys"))
}

// Returns an array of keys with recent changes to their values. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976184-changedkeys?language=objc
func (r_ RecordKeyValueSettingObject) ChangedKeys() []RecordFieldKey {
	rv := objc.Call[[]RecordFieldKey](r_, objc.Sel("changedKeys"))
	return rv
}

func (r_ RecordKeyValueSettingObject) HasObjectForKeyedSubscript() bool {
	return r_.RespondsToSelector(objc.Sel("objectForKeyedSubscript:"))
}

// Returns the object that the record stores for the specified key. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976186-objectforkeyedsubscript?language=objc
func (r_ RecordKeyValueSettingObject) ObjectForKeyedSubscript(key RecordFieldKey) RecordValueObject {
	rv := objc.Call[RecordValueObject](r_, objc.Sel("objectForKeyedSubscript:"), key)
	return rv
}

func (r_ RecordKeyValueSettingObject) HasSetObjectForKeyedSubscript() bool {
	return r_.RespondsToSelector(objc.Sel("setObject:forKeyedSubscript:"))
}

// Stores an object in the record using the specified key. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976188-setobject?language=objc
func (r_ RecordKeyValueSettingObject) SetObjectForKeyedSubscript(object RecordValueObject, key RecordFieldKey) {
	po0 := objc.WrapAsProtocol("CKRecordValue", object)
	objc.Call[objc.Void](r_, objc.Sel("setObject:forKeyedSubscript:"), po0, key)
}

func (r_ RecordKeyValueSettingObject) HasSetObjectForKey() bool {
	return r_.RespondsToSelector(objc.Sel("setObject:forKey:"))
}

// Stores an object in the record using the specified key. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976187-setobject?language=objc
func (r_ RecordKeyValueSettingObject) SetObjectForKey(object RecordValueObject, key RecordFieldKey) {
	po0 := objc.WrapAsProtocol("CKRecordValue", object)
	objc.Call[objc.Void](r_, objc.Sel("setObject:forKey:"), po0, key)
}

func (r_ RecordKeyValueSettingObject) HasObjectForKey() bool {
	return r_.RespondsToSelector(objc.Sel("objectForKey:"))
}

// Returns the object that the record stores for the specified key. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/cloudkit/ckrecordkeyvaluesetting/2976185-objectforkey?language=objc
func (r_ RecordKeyValueSettingObject) ObjectForKey(key RecordFieldKey) RecordValueObject {
	rv := objc.Call[RecordValueObject](r_, objc.Sel("objectForKey:"), key)
	return rv
}
