// Code generated by DarwinKit. DO NOT EDIT.

package webkit

import (
	"github.com/progrium/darwinkit/objc"
)

// This protocol is adopted by document representation classes that handle specific MIME types. You can implement your own document view classes and document representation classes to render data for specific MIME types, and register those classes using the WebFrame [webkit/webview/registerviewclass] method. [Full Topic]
//
// [Full Topic]: https://developer.apple.com/documentation/webkit/webdocumentrepresentation?language=objc
type PWebDocumentRepresentation interface {
}

// ensure impl type implements protocol interface
var _ PWebDocumentRepresentation = (*WebDocumentRepresentationObject)(nil)

// A concrete type for the [PWebDocumentRepresentation] protocol.
type WebDocumentRepresentationObject struct {
	objc.Object
}
