// Code generated by DarwinKit. DO NOT EDIT.

// Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.
//
// [Apple Documentation]
//
// [Apple Documentation]: https://developer.apple.com/documentation/avfoundation?language=objc
package avfoundation
