// Code generated by DarwinKit. DO NOT EDIT.

#import "Metal/Metal.h"

void importMetalProtocols() {
    id o;
    o = @protocol(MTLAccelerationStructure);
    o = @protocol(MTLAccelerationStructureCommandEncoder);
    o = @protocol(MTLArgumentEncoder);
    o = @protocol(MTLBinaryArchive);
    o = @protocol(MTLBlitCommandEncoder);
    o = @protocol(MTLBuffer);
    o = @protocol(MTLCaptureScope);
    o = @protocol(MTLCommandBuffer);
    o = @protocol(MTLCommandBufferEncoderInfo);
    o = @protocol(MTLCommandEncoder);
    o = @protocol(MTLCommandQueue);
    o = @protocol(MTLComputeCommandEncoder);
    o = @protocol(MTLComputePipelineState);
    o = @protocol(MTLCounter);
    o = @protocol(MTLCounterSampleBuffer);
    o = @protocol(MTLCounterSet);
    o = @protocol(MTLDepthStencilState);
    o = @protocol(MTLDevice);
    o = @protocol(MTLDrawable);
    o = @protocol(MTLDynamicLibrary);
    o = @protocol(MTLEvent);
    o = @protocol(MTLFence);
    o = @protocol(MTLFunction);
    o = @protocol(MTLFunctionHandle);
    o = @protocol(MTLFunctionLog);
    o = @protocol(MTLFunctionLogDebugLocation);
    o = @protocol(MTLFunctionStitchingAttribute);
    o = @protocol(MTLFunctionStitchingNode);
    o = @protocol(MTLHeap);
    o = @protocol(MTLIndirectCommandBuffer);
    o = @protocol(MTLIndirectComputeCommand);
    o = @protocol(MTLIndirectRenderCommand);
    o = @protocol(MTLIntersectionFunctionTable);
    o = @protocol(MTLLibrary);
    o = @protocol(MTLLogContainer);
    o = @protocol(MTLParallelRenderCommandEncoder);
    o = @protocol(MTLRasterizationRateMap);
    o = @protocol(MTLRenderCommandEncoder);
    o = @protocol(MTLRenderPipelineState);
    o = @protocol(MTLResource);
    o = @protocol(MTLResourceStateCommandEncoder);
    o = @protocol(MTLSamplerState);
    o = @protocol(MTLSharedEvent);
    o = @protocol(MTLTexture);
    o = @protocol(MTLVisibleFunctionTable);
}
