on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [oldstable]
        os: [macos-11, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: |
        TAGS=${{ matrix.os }}
        TAGS=${TAGS//-} # remove dash
        go test -tags $TAGS -v ./...
    - name: Build helloworld
      run: |
        TAGS=${{ matrix.os }}
        TAGS=${TAGS//-} # remove dash
        go build -tags $TAGS ./macos/_examples/helloworld